name: nmr
channels:
  - defaults
  - conda-forge
dependencies:
  - appdirs=1.4.4
  - biopython=1.81
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - cftime=1.6.2
  - charset-normalizer=2.0.4
  - contourpy=1.0.5
  - cryptography=39.0.1
  - curl=7.30.0
  - cycler=0.11.0
  - fasteners=0.16.3
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - griddataformats=1.0.1
  - gsd=2.8.1
  - h5py=3.7.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - idna=3.4
  - jbig=2.1
  - joblib=1.1.1
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.88.1
  - libcxx=14.0.6
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.52.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libzip=1.9.2
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib-base=3.7.1
  - mdanalysis=2.4.3
  - mmtf-python=1.1.3
  - mrcfile=1.4.3
  - msgpack-python=1.0.3
  - munkres=1.1.4
  - ncurses=6.3
  - netcdf4=1.6.2
  - networkx=2.8.4
  - numpy=1.24.2
  - openssl=3.1.0
  - packaging=23.0
  - pandas=2.0.0
  - pbr=5.6.0
  - pillow=9.4.0
  - pip=23.1
  - pooch=1.4.0
  - pycparser=2.21
  - pyedr=0.7.1
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytng=0.3.0
  - pytz=2022.7
  - readline=8.2
  - requests=2.28.1
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - seaborn=0.12.2
  - setuptools=67.6.1
  - six=1.16.0
  - threadpoolctl=2.2.0
  - tidynamics=1.0.0
  - tk=8.6.12
  - tqdm=4.65.0
  - tzdata=2023c
  - urllib3=1.26.15
  - wheel=0.40.0
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - cython==0.29.34
      - deprecated==1.2.13
      - hopcroftkarp==1.2.5
      - jinja2==3.1.2
      - kmapper==2.0.1
      - markupsafe==2.1.2
      - persim==0.3.1
      - pynmrstar==3.3.2
      - ripser==0.6.4
      - scikit-tda==1.0.0
      - tadasets==0.0.4
      - wrapt==1.15.0
